### PR TITLE
Joined date fixed on User profile 

### LINKED ISSUE #2118: Incorrect joining date on User profile
**Describe the bug**
The joining date for the USER is static and is set to " 1st May, 2021 " which is incorrect .

**To Reproduce**

1.Setting up Talawa-api and Talawa-admin
2.Register and Login as a USER
3.Navigate to the USER dashboard
4.Under the USER profile the incorrect joining date can be seen .

**Expected behavior**
The profile section should display the date when the USER created the account dynamically.

**Actual behavior**
Static rendering of the joining date as " 1st May, 2021 ".

**Screenshots**
Screenshot 2024-07-25 at 2 17 04 AM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Saanvi26**
**What kind of change does this PR introduce?**

BugFix
Fixed the joining date of user on the user profile section.

**Issue Number:**

Fixes #2118 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Screenshot 2024-07-25 at 1 20 56 PM

**If relevant, did you update the documentation?**

NA

**Summary**

The joining date for the USER was static and was set to " 1st May, 2021 " which was incorrect . Fixed this by dynamically rendering the actual user profile createdAt date.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced user profile data by including the account creation date.
	- Introduced a new date formatting function for improved readability of the join date.
  
- **Bug Fixes**
	- Updated test cases to reflect the new `createdAt` property and adjust expected values.
  
- **Documentation**
	- Improved user interface to dynamically display the user's join date instead of a hardcoded value.

### CODE REVIEW

File: src/components/UserProfileSettings/UserProfile.tsx [hunk 1]
```diff
@@ -8,13 +8,25 @@ import styles from './UserProfileSettings.module.css';
 interface InterfaceUserProfile {
   firstName: string;
   lastName: string;
+  createdAt: string;
   email: string;
   image: string;
 }
+const prettyDate = (param: string): string => {
```
Comment (varshith257) [inline src/components/UserProfileSettings/UserProfile.tsx:15]: Can it be `joinedDate` to indicate function behaviour?

**Review by varshith257 — CHANGES_REQUESTED** [review]

File: src/components/UserProfileSettings/UserProfile.tsx (hunk 1 above)
Comment (Saanvi26) [reply src/components/UserProfileSettings/UserProfile.tsx:15]: Yes Sure

**Review by varshith257 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]
