### PR TITLE
 Fixed error message in PostCard.tsx

### LINKED ISSUE #3142: Bug Report: Improve Comment Validation Error Message for Users
**Describe the bug**
When a user submits an empty comment, the application currently shows a technical error message: "Comment validation failed: text: Path 'text' is required." This message is intended for developers and is not suitable for users. It should be replaced with a more user-friendly message like "Please enter a comment before submitting." The original technical message should be kept in the logs for developer reference, but not displayed to end-users.

**To Reproduce**

1. Go to the comment section.
2. Leave the comment field empty.
3. Submit the comment.
4. Observe the technical error message displayed.

**Expected behavior**
A user-friendly error message like "Please enter a comment before submitting."

**Actual behavior**
A technical error message: "Comment validation failed: text: Path 'text' is required."

**Screenshots**
Before Fix:
Screenshot 2025-01-05 015249
After Fix: 
Screenshot 2025-01-05 021900

**Additional details**
I've implemented a fix locally by updating the error handling logic to show a more appropriate message to the users while keeping the developer-specific message for internal logs.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Nivedita-Chhokar**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #3142

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Before :
Screenshot 2025-01-05 015249

After :
Screenshot 2025-01-05 021900

https://github.com/user-attachments/assets/aa75da2f-c21d-40be-8ddf-aee7b6234f4a

**If relevant, did you update the documentation?**
No

**Summary**

This PR resolves the issue where submitting an empty comment displayed a technical error message (Comment validation failed: text: Path 'text' is required.). The error message is now replaced with a user-friendly one (Please enter a comment before submitting.), enhancing the user experience. The technical message remains in the logs for developers.

**Does this PR introduce a breaking change?**

No

**Other information**

None

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved error handling for comment submission.
	- Enhanced user feedback for comment-related errors.
	- Refined error message display to provide clearer guidance to users when submitting comments.
  
- **New Features**
	- Added user-friendly error messages for empty comment submissions in multiple languages (English, French, Hindi, Spanish, Chinese).
  
- **Tests**
	- Introduced new test cases for handling empty comment submissions and network errors in the PostCard component.

### CODE REVIEW

File: src/components/UserPortal/PostCard/PostCard.tsx [hunk 1]
```diff
@@ -225,7 +225,16 @@ export default function postCard(props: InterfacePostCard): JSX.Element {
         setComments([...comments, newComment]);
       }
     } catch (error: unknown) {
-      errorHandler(t, error);
+      if (error instanceof Error) {
+        error.message
+          .replace(/^Comment validation failed:\s*/, '')
+          .replace(/Path `text` is required\./, '')
```
Comment (palisadoes) [inline src/components/UserPortal/PostCard/PostCard.tsx:231]: 1. Please add tests for the code you added so that we don't have a repeat of the error
2. You need to use translations for this in all languages. A search and replace isn't good enough

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please add tests for the code you added so that we don't have a repeat of the error
2. You need to use translations for this in all languages. A search and replace isn't good enough

File: src/components/UserPortal/PostCard/PostCard.tsx (hunk 1 above)
Comment (Nivedita-Chhokar) [reply src/components/UserPortal/PostCard/PostCard.tsx:231]: Thank you for the feedback! I'll work on adding the necessary tests and updating the implementation to use translations. I'll let you know once the changes are ready for review.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please add tests as shown here. Click the CodeCov links above to see for yourself

1. https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/3152?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation
    image
1. Please add translations for the text. It's only in English.

**Comment by palisadoes** [comment]
Your tests are failing. Please don't  assign reviewers if they are. Please be considerate of our time.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test

File: src/components/UserPortal/PostCard/PostCard.tsx [hunk 2]
```diff
@@ -225,7 +231,19 @@ export default function postCard(props: InterfacePostCard): JSX.Element {
...
       }
     } catch (error: unknown) {
-      errorHandler(t, error);
+      // Handle errors
+      if (error instanceof Error) {
+        if (
+          error.message.includes('Comment validation failed') &&
+          error.message.includes('Path text is required')
+        ) {
+          toast.error('Please enter a comment before submitting.');
```
Comment (rishav-jha-mech) [inline src/components/UserPortal/PostCard/PostCard.tsx:240]: @Nivedita-Chhokar These errors should also be supported in multiple languages, add the translation for these in respective translation.json files and re request for review

File: src/components/UserPortal/PostCard/PostCard.spec.tsx [hunk 3]
```diff
@@ -661,6 +661,61 @@ describe('Testing PostCard Component [User Portal]', () => {
...
+      </MockedProvider>,
+    );
+
+    userEvent.click(screen.getByTestId('viewPostBtn')); // Open the post view
+    userEvent.type(screen.getByTestId('commentInput'), ''); // Type an empty comment
+    userEvent.click(screen.getByTestId('createCommentBtn'));
+
+    await waitFor(() => {
+      expect(toast.error).toHaveBeenCalledWith(
+        i18nForTest.t('postCard.emptyCommentError'),
```
Comment (rishav-jha-mech) [inline src/components/UserPortal/PostCard/PostCard.spec.tsx:714]: This is good, but to have a good code coverage you need to write tests for other error messages that you have added as well

File: src/components/UserPortal/PostCard/PostCard.tsx (hunk 2 above)
Comment (rishav-jha-mech) [inline src/components/UserPortal/PostCard/PostCard.tsx:240]: To have multilanguage support this line should be replaced by this
```
  toast.error(t('emptyCommentError'));
```

**Comment by Nivedita-Chhokar** [comment]
@rishav-jha-mech Thanks for reviewing. I'll make the necessary changes.

**Comment by Nivedita-Chhokar** [comment]
@coderabbitai full review

**Comment by Nivedita-Chhokar** [comment]
@rishav-jha-mech Could you please review my commit? All of my test cases were passing initially, but after Code Rabbit suggested some changes, I added additional test cases, including edge cases. However, Code Rabbit is still not approving it.

File: src/components/UserPortal/PostCard/PostCard.spec.tsx [hunk 4]
```diff
@@ -661,6 +661,125 @@ describe('Testing PostCard Component [User Portal]', () => {
     await wait();
   });
 
+  test('Comment validation displays an error toast when an empty comment is submitted', async () => {
+    console.log('Starting empty comment validation test');
```
Comment (rishav-jha-mech) [inline src/components/UserPortal/PostCard/PostCard.spec.tsx:665]: @Nivedita-Chhokar code rabbit is asking you to remove this line

Comment (Nivedita-Chhokar) [reply src/components/UserPortal/PostCard/PostCard.spec.tsx:665]: @rishav-jha-mech Thank you for your review. I'll remove that line, but could you share your thoughts on the other suggestions made by Code Rabbit? Also, if you have any additional recommendations, I'd appreciate them.

**Review by palisadoes — APPROVED** [review]
