### PR TITLE
fix: #2508 Refactor CSS files in src/screens/Leaderboard

### LINKED ISSUE #2508: Refactor CSS files in src/screens/Leaderboard
# Refactor CSS files in src/screens/Leaderboard

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by pranavnathe**
**What kind of change does this PR introduce?**

Refactoring of CSS files related to the Leaderboard screen.

**Issue Number:**

Fixes #2508 

**If relevant, did you update the documentation?**

No

**Summary**

This PR refactors the CSS for the Leaderboard screen by moving relevant styles to the global app.module.css file.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a new CSS class for smaller table images, enhancing the display of avatars in the leaderboard.
	- Added a new CSS variable for consistent sizing of small images.

- **Bug Fixes**
	- Updated styling references to ensure proper rendering of leaderboard components.

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

File: src/screens/Leaderboard/Leaderboard.tsx [hunk 1]
```diff
@@ -200,7 +200,7 @@ function leaderboard(): JSX.Element {
                   <Avatar
                     key={_id + '1'}
                     containerStyle={styles.imageContainer}
-                    avatarStyle={styles.TableImage}
+                    avatarStyle={styles.TableImageSmall}
```
Comment (palisadoes) [inline src/screens/Leaderboard/Leaderboard.tsx:203]: Why was this changed?

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comment

File: src/screens/Leaderboard/Leaderboard.tsx (hunk 1 above)
Comment (pranavnathe) [reply src/screens/Leaderboard/Leaderboard.tsx:203]: Changed to styles.TableImageSmall because the original size was causing the avatar images to overflow their space, affecting the layout.

TableImageSmall

**Comment by palisadoes** [comment]
Thanks. Please fix the conflicting file so we can merge

**Review by palisadoes — APPROVED** [review]
