### PR TITLE
Fixed Format of params passed via Url in User Portal

### LINKED ISSUE #1829: Bug Report: OrgID being passed in Wrong Format in UserPortal
**Describe the bug**
The Organization ID being set in URL should be set as URL parameter instead of URL query vars. The following inproper format leads to events and rest of entities in UserPortal not being rendered.

**To Reproduce**

1. Login To User Portal
2. Select a Organization
3. Open Events/Donation Page 
4. Events/Donations wont render due to failing graphql queries

**Expected behavior**
OrgID should be passed as params without any 'id=' prefix so that proper orgId is passed to various graphQl queries

**Actual behavior**
OrgID is passed as params but with 'id=' prefix leading to failings graphQl queries

**Screenshots**
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by GlenDsza**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1829 

**Did you add tests for your changes?**

Yes 

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/0cb315c6-4147-4ada-94ff-2be038174b19

**Summary**

- Fixed the way organizationId is passed in Url Params.
- Updated Test case in Home.tsx to handle above change

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

File: src/screens/UserPortal/Home/Home.tsx [hunk 1]
```diff
@@ -90,8 +90,8 @@ export default function home(): JSX.Element {
   const [filteredAd, setFilteredAd] = useState<InterfaceAdContent[]>([]);
   const [showModal, setShowModal] = useState<boolean>(false);
   const { orgId } = useParams();
-  const organizationId = orgId?.split('=')[1] || null;
-  if (!organizationId) {
+  console.log(typeof orgId, orgId);
```
Comment (pranshugupta54) [inline src/screens/UserPortal/Home/Home.tsx:93]: Can avoid logging the data (Tests get very long console due to this)

Comment (GlenDsza) [reply src/screens/UserPortal/Home/Home.tsx]: Yess forgot about it

**Review by palisadoes — APPROVED** [review]
