### PR TITLE
[FIX] User Portal: People Page Violates The Figma Style Guide

### LINKED ISSUE #3199: Figma User Portal: People Page Violates The Figma Style Guide
## Post a video of your work in the PR

**Describe the bug**

1. User Portal: Organization Left Drawer Violates The Figma Style Guide

**To Reproduce**

1. Style Related
    1. Login to the app as a User
    2. Select an organization
    3. Select people
    5. The figma guide is not followed fully

**Expected behavior**

1. The screens shown must conform to Figma
4. This must apply to the following where relevant:
    1. Users
    3. Admins
    6. SuperAdmins
1. Tests must be written to ensure this does not happen again
2. The CSS must be consolidated into this file using variables wherever possible
    1. `src/style/app.module.css`

**Other**

1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
1. When in doubt about colors, take cues from other similar elements in this file and the PR mentioned in the issue.
    1. https://www.figma.com/design/dmKt00m9GVSeA1nebnkxql/Untitled?node-id=0-1&node-type=canvas&t=TPzfh1DE9IxjzsEe-0
1. The desired single CSS file is:
    1. `src/style/app.module.css`
        1. Convert all code files to use this file.
        1. Delete all CSS files in this code path and below mentioned in the title. The `src/style/app.module.css` file must be the only source of CSS
1. Use no CSS in:
    1. `assets/css/app.css`    
1. Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
    1. For example `--search-button-bg` is much better than `--light-blue` 
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/3296
1. When refactoring modals, please refer to this PR that has created a standardized design patter for them.
   1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2984
1. Remove all references to HTML color codes in the files you edit except in `src/style/app.module.css`
1. Buttons, and dropdowns must only have shadows when there is a mouse hover. Their color must not change
1. Search boxes must only have shadows when selected

**Screenshots**

image

**Additional details**
1. Background color guide - Use these instead of those that may be different in sample pages below. Our Figma design is not consistent
    image
1. Update as per Figma with these modifications
    image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by hustlernik**
**What kind of change does this PR introduce?**

UI fix according to figma.

**Issue Number:**

Fixes #3199 

**Snapshots/Videos:**

https://github.com/user-attachments/assets/193692e6-221b-448b-83d8-497106d3288d

**Does this PR introduce a breaking change?**

No

### CodeRabbit AI Review
- [ ] I have reviewed and addressed all critical issues flagged by CodeRabbit AI
- [ ] I have implemented or provided justification for each non-critical suggestion
- [ ] I have documented my reasoning in the PR comments where CodeRabbit AI suggestions were not implemented

### Test Coverage
- [ ] I have written tests for all new changes/features
- [ ] I have verified that test coverage meets or exceeds 95%
- [ ] I have run the test suite locally and all tests pass

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Style Changes**
	- Removed outdated styles from the PeopleCard and People components.
	- Updated CSS classes for improved styling in the People component.
	- Consolidated styles into `app.module.css`.

- **UI Improvements**
	- Redesigned search functionality layout.
	- Streamlined component structure for better usability.
	- Enhanced visual consistency across people-related components.
	- Introduced new styling options for various elements in the people feature.

- **Documentation**
	- Added documentation for new variables related to organization tags.
	- Updated documentation for existing variables to reflect changes in structure and definitions.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please make a minor commit to restart the GitHub workflow. It should fix the application testing

File: src/screens/UserPortal/People/People.tsx [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
 import {
   ORGANIZATIONS_MEMBER_CONNECTION_LIST,
   ORGANIZATION_ADMINS_LIST,
 } from 'GraphQl/Queries/Queries';
 import { useQuery } from '@apollo/client';
-import { FilterAltOutlined, SearchOutlined } from '@mui/icons-material';
-import styles from './People.module.css';
+import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';
+import { FilterAltOutlined } from '@mui/icons-material';
+import styles from '../../../style/app.module.css';
```
Comment (palisadoes) [inline src/screens/UserPortal/People/People.tsx:12]: 1. Make this file use CSS exclusively from `src/style/app.module.css`, with the exception of package based CSS.
1. Delete the CSS file it currently uses.
1. Use no CSS in `assets/css/app.css`
1. This will help with future attempts to having Dark Mode
1. Use a variable from `src/style/app.module.css` .
1. If this is the sidebar color, name it `--side-bar` , or whatever this section of code is defining. 

- https://github.com/PalisadoesFoundation/talawa-admin/issues/3296

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please see comments
2. Add tests for the files you've updated to get as close to 100% test coverage as possible
3. Ensure code rabbit approves your PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Buttons, and dropdowns must only have shadows when there is a mouse hover. Their color must not change
2. Search boxes must only have shadows when selected
3. When clicked, there is a green outline
    image
4. The button becomes transparent
    image
1. Read the requirements carefully in the issue
    image

File: src/style/app.module.css [hunk 2]
```diff
@@ -6390,3 +6411,97 @@ button[data-testid='createPostBtn'] {
...
+  display: flex;
+}
+
+.align_center {
+  align-self: center;
+}
+
+.people_role {
+  width: 75%;
+  border: 1px solid #dee2e6;
```
Comment (palisadoes) [inline src/style/app.module.css:6436]: Use a variable name not the hex code. Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

**Comment by hustlernik** [comment]
@coderabbitai full review

File: src/style/app.module.css [hunk 3]
```diff
@@ -6390,3 +6411,97 @@ button[data-testid='createPostBtn'] {
...
+.gap {
+  gap: 20px;
+}
+
+.semiBold {
+  font-weight: 500;
+}
+
+.placeholderColor::placeholder {
+  color: #737373;
```
Comment (palisadoes) [inline src/style/app.module.css:6479]: Use a variable name not the hex code. Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 4]
```diff
@@ -6390,3 +6411,97 @@ button[data-testid='createPostBtn'] {
...
+  border-radius: 8px;
+}
+
+.bottomRadius {
+  border-bottom-left-radius: 24px;
+  border-bottom-right-radius: 24px;
+}
+
+.shadow {
+  box-shadow: 5px 5px 4px 0px #d9d9d9;
```
Comment (palisadoes) [inline src/style/app.module.css:6456]: Use a variable name not the hex code. Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 5]
```diff
@@ -6390,3 +6411,97 @@ button[data-testid='createPostBtn'] {
...
+}
+
+.backgroundWhite {
+  background-color: white;
```
Comment (palisadoes) [inline src/style/app.module.css:6460]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 6]
```diff
@@ -6390,3 +6411,97 @@ button[data-testid='createPostBtn'] {
...
+  display: flex;
+  align-items: center;
+  justify-content: space-between;
+  margin-right: 50px;
+}
+
+.people_card_main_container {
+  display: flex;
+  flex-direction: column;
+  border: 1px solid var(--grey-light);
```
Comment (palisadoes) [inline src/style/app.module.css:6492]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 7]
```diff
@@ -6390,3 +6411,97 @@ button[data-testid='createPostBtn'] {
...
+  padding: 1rem;
+  padding-left: 1.5rem;
+  padding-right: 1.5rem;
+  margin-top: 0;
+  gap: var(--spacing-lg, 1.25rem);
+  border-bottom-left-radius: 24px;
+  border-bottom-right-radius: 24px;
+  background-color: var(--bs-white);
```
Comment (palisadoes) [inline src/style/app.module.css:6500]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 8]
```diff
@@ -2618,7 +2625,12 @@ input[type='radio']:checked + label:hover {
   color: var(--grey-bg-color-dark);
 }
 
-.topRadius {
+.people_card_header {
+  background-color: var(--grey-light);
+  display: flex;
+  border: 1px solid var(--grey-border);
```
Comment (palisadoes) [inline src/style/app.module.css:2631]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 9]
```diff
@@ -2618,7 +2625,12 @@ input[type='radio']:checked + label:hover {
   color: var(--grey-bg-color-dark);
 }
 
-.topRadius {
+.people_card_header {
+  background-color: var(--grey-light);
```
Comment (palisadoes) [inline src/style/app.module.css:2629]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 10]
```diff
@@ -514,26 +512,35 @@
...
-  background-color: var(--search-button-hover-bg, #286fe0) !important;
-  border-color: transparent !important;
+  background-color: var(--search-button-bg) !important;
+  border-color: var(--search-button-bg) !important;
+  transform: scale(0.98);
+}
+
+.searchButton:focus {
+  outline: none !important;
+  box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.5);
```
Comment (palisadoes) [inline src/style/app.module.css:543]: Use a variable name not the hex/rgba code. Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 11]
```diff
@@ -514,26 +512,35 @@
...
+    box-shadow 0.2s ease,
+    transform 0.2s ease;
 }
 
 .searchButton:hover {
-  background-color: var(--search-button-hover-bg, var(--light-blue-color));
-  border-color: var(--search-button-hover-bg, var(--light-blue-color));
+  background-color: var(--search-button-bg) !important;
+  border-color: var(--search-button-bg) !important;
+  box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
```
Comment (palisadoes) [inline src/style/app.module.css:532]: Use a variable name not the hex/rgba code. Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 12]
```diff
@@ -498,7 +492,11 @@
 }
 
 .inputField:focus {
-  box-shadow: 0 0 0 0.25rem var(--light-blue);
+  border: 0.1px solid var(--dimp-white) !important;
```
Comment (palisadoes) [inline src/style/app.module.css:495]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 13]
```diff
@@ -498,7 +492,11 @@
...
+  background-color: var(--bs-white) !important;
```
Comment (palisadoes) [inline src/style/app.module.css:496]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 14]
```diff
@@ -498,7 +492,11 @@
...
+  box-shadow: 4px 4px 8px var(--black-shadow-color);
```
Comment (palisadoes) [inline src/style/app.module.css:497]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comments

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please get the code coverage for the file you edited as close to 100% as possible.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/3310#issuecomment-2599646157
image

File: src/style/app.module.css [hunk 15]
```diff
@@ -338,8 +351,8 @@
     :disabled,
     :checked
   ) {
-  background-color: transparent !important;
-  border: 1px solid var(--brown-color);
+  box-shadow: 2.5px 2.5px 2.5px rgba(0, 0, 0, 0.3);
```
Comment (palisadoes) [inline src/style/app.module.css:354]: Use a variable name not the hex/rgba code (Use 8 digit HTML codes for transparency if necessary). Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.  
- For example `--search-button-bg` is much better than `--light-blue`

File: src/style/app.module.css [hunk 16]
```diff
@@ -338,8 +351,8 @@
...
+  border: 1px solid var(--brown-color) !important;
   color: var(--brown-color) !important;
```
Comment (palisadoes) [inline src/style/app.module.css:356]: Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
- For example `--search-button-bg` is much better than `--light-blue`

**Comment by hustlernik** [comment]
image

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comments

**Comment by hustlernik** [comment]
image

**Comment by palisadoes** [comment]
Almost done.

**Review by palisadoes — APPROVED** [review]
