### PR TITLE
Fix : #2112 by including client side validation for donation amount.

### LINKED ISSUE #2112: Text Input Allowed in Donation Field Causes Runtime Error and Incorrect Success Message
**Describe the bug**
Currently in donation page the DONATION field allows in text and its even makes toast appear as sucessfully **_img 2_** while giving a following error Uncaught runtime errors

**To Reproduce**

1. go to donation page
2. type random text and click on button
3.  you get an error and when you close the error you'll get successfull toast message

**Expected behavior**
1. Donation field should not allow any text field
2. even if it allows a text we can have error toast and not let it send sucessfull

**Screenshots**
**img 1**
Screenshot 2024-07-23 124924
**img 2**
Screenshot 2024-07-23 124904

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AnshulKahar2729**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #2112 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
https://github.com/user-attachments/assets/c3831507-2718-4f8b-8993-ba06a17cd14c

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Added user guidance for donation input, including detailed descriptions and validation prompts in multiple languages.
- **Bug Fixes**
	- Improved input validation for donation amounts to prevent non-numeric entries and ensure limits are respected, enhancing user feedback.
- **Tests**
	- Enhanced test coverage with new cases for handling invalid donation amounts, ensuring appropriate error messages are displayed.

### CODE REVIEW

**Comment by AnshulKahar2729** [comment]
@palisadoes  PTAL

**Review by palisadoes — CHANGES_REQUESTED** [review]
Why aren't there translations for the other languages?

**Comment by AnshulKahar2729** [comment]
> Why aren't there translations for the other languages?

Done, added translation for all the languages.

**Comment by AnshulKahar2729** [comment]
> Why aren't there translations for the other languages?


Done, added translation for all the languages, can you PTAL @palisadoes ?

**Review by varshith257 — CHANGES_REQUESTED** [review]
I have noticed a couple of areas where we can improve:
 
1.  The code only checks if the amount is a non-empty string and if it is a number but it didn't enforce any minimum or maximum donation limits which we can see in many payment/donation forms. I think we can add an additional check to ensure the donation amount is a positive number and falls within a predefined range e.g., $1 to $10,000

2. I can see there is no check to trim any whitespace from the amount input before validation. 
We can add something like this for better usability:
```
const formattedAmount = parseFloat(amount.trim()).toFixed(2);
```
3. Add an additional check for negative values too

**Comment by AnshulKahar2729** [comment]
> I have noticed a couple of areas where we can improve:
> 
> 1. The code only checks if the amount is a non-empty string and if it is a number but it didn't enforce any minimum or maximum donation limits which we can see in many payment/donation forms. I think we can add an additional check to ensure the donation amount is a positive number and falls within a predefined range e.g., $1 to $10,000
> 2. I can see there is no check to trim any whitespace from the amount input before validation.
>    We can add something like this for better usability:
> 
> ```
> const formattedAmount = parseFloat(amount.trim()).toFixed(2);
> ```
> 
> 3. Add an additional check for negative values too
> 
> cc: @palisadoes Do you like add any comments about MIN and MAX range of amount

Done, improved the following things, LMK if anything else is required, I am happy to improve it.

**Comment by AnshulKahar2729** [comment]
@varshith257 can you finally review it, I keep the logic simple as this issue was more for avoiding the runtime error on submitting the invalid value.

**Comment by varshith257** [comment]
@AnshulKahar2729 Let's wait for @palisadoes review on above changes I have suggested

**Comment by AnshulKahar2729** [comment]
> @AnshulKahar2729 Let's wait for @palisadoes review on above changes I have suggested 

@palisadoes can you review it once. For ranges limit, I think we can create a different issue for that since and have a proper discussion on that.

**Comment by AnshulKahar2729** [comment]
> > @AnshulKahar2729 Let's wait for @palisadoes review on above changes I have suggested 
> 
> @palisadoes can you look it over once? For range limits, we can create a different issue for that and have a proper discussion on that.

@varshith257 @palisadoes can you guys please review this, if any improvements are required, I can do that. Since I have been assigned this issue, I am not able to pick another one.

**Comment by varshith257** [comment]
@AnshulKahar2729 You can tag this PR in #pr-status channel in the slack to get quick attention of Peter or other reviewer s too.

Overall the changes are good and I am waiting for Peter's review of adding of suggested changes before I approve this PR.

**Comment by AnshulKahar2729** [comment]
> @AnshulKahar2729 You can tag this PR in #pr-status channel in the slack to get quick attention of Peter or other reviewer s too.
> 
> Overall the changes are good and I am waiting for Peter's review of adding of suggested changes before I approve this PR.

Ok thanks for the information.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@varshith257 PTAL

**Review by varshith257 — DISMISSED** [review]
LGTM.

**Comment by varshith257** [comment]
Nice work 💪

File: src/screens/UserPortal/Donate/Donate.tsx [hunk 1]
```diff
@@ -128,14 +128,36 @@ export default function donate(): JSX.Element {
...
   const donateToOrg = (): void => {
+    // check if the amount is non empty and is a number
+    if (amount === '' || Number.isNaN(Number(amount))) {
+      toast.error(t(`invalidAmount`));
+      return;
+    }
+
+    // check if the amount is non negative and within the range
+    const minDonation = 1;
+    const maxDonation = 10000;
```
Comment (palisadoes) [inline src/screens/UserPortal/Donate/Donate.tsx:139]: 1. Why was this value selected as the maximum? 
2. Does it take into consideration all exchange rates across the world? 
    - For example 10,000,000 Venezuelan Bolivares are worth just under US$3.00 at current exchange rates.

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Why was this 10000 selected as the maximum donation? 
2. Does it take into consideration all exchange rates across the world? 
    - For example 10,000,000 Venezuelan Bolivares are worth just under US$3.00 at current exchange rates.

File: src/screens/UserPortal/Donate/Donate.tsx (hunk 1 above)
Comment (AnshulKahar2729) [reply src/screens/UserPortal/Donate/Donate.tsx:139]: well, for that I would need @varshith257's help because he suggested that.

Comment (palisadoes) [reply src/screens/UserPortal/Donate/Donate.tsx:139]: Please use your initiative and create a usable solution.

**Comment by varshith257** [comment]
@AnshulKahar2729  Better create a new ticket with follow up with the changes I suggested but we need to ensure this need to be implemented. Revert the changes done in this PR of my suggestions and I will follow up on new issue

**Comment by varshith257** [comment]
@palisadoes What can be the Max-Limit can be donated in a single transaction or if we think we don't strictly needed we keep this end of MAX_LIMIT with an positive integer. But it could be good if we have certain limit.

And if our intention to add multiple currencies support then we better integrate this functionality when payments support is added

**Comment by palisadoes** [comment]
It's not that multiple currencies need to be supported now. It's that we must not have an artificial limit if the organization is using a weak currency because they are in a country experiencing high inflation. We need a limit, but 10,000 is too low. 

Even in strong economies 10,000 is too low. For example 10,000 Rupees is currently US$120 , 10,000 Japanese Yen is currently valued at US$70. The app would be unusable in these economies.

Think of a better solution

**Comment by AnshulKahar2729** [comment]
> would be unusable in these

I would like to work on that too, but it would be better if either of you create a proper new issue with proper description and discussion.

File: src/screens/UserPortal/Donate/Donate.tsx (hunk 1 above)
Comment (AnshulKahar2729) [reply src/screens/UserPortal/Donate/Donate.tsx]: I think it would be better if you guys create a new issue for that. The reason is we need proper discussion for the max limit according to our app over all things.

**Comment by palisadoes** [comment]
1. Set it to 10,000,000
2. That should be enough for most currency cases

**Comment by AnshulKahar2729** [comment]
> 1. Set it to 10,000,000
> 2. That should be enough for most currency cases

Ok, I will do that as per instructed by you. But, how about handling the max limit according to the chosen currency, I mean that's how it should actually work. 

And still if you want to go with a hardcoded max limit, I will do that, LMK how you want to do it finally.

**Comment by palisadoes** [comment]
1. Use the same value for all currencies.
2. We'll need to integrate with live exchange rate data otherwise for ease of use. That would add too much complexity

**Comment by AnshulKahar2729** [comment]
@palisadoes Done, with everything.

**Review by varshith257 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]
