### PR TITLE
changed the handleSearchByName function in searchByName in Roles page

### LINKED ISSUE #716: Bug Report - Search for users in Roles Section is laggy and not consistent
**Describe the bug**
When logged in as the superadmin, in the roles section of the website, searching for users according to their name is not consistent ( it is one step behind )

**To Reproduce**

1. Log in as a super admin
2. Go to the Roles section of the website
3. Try searching for a name ( letter by letter )

**Expected behavior**
It is expected that the search should be as smooth and consistent as possible!

**Screenshots**
image

**Additional details**
Here's a video example :-

https://user-images.githubusercontent.com/97829544/225363433-26ca22a7-227e-4ff0-9967-baf938845137.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Pranauv-Kumar1803**
**What kind of change does this PR introduce?**
While searching for users by their first name in the Roles page, it will show the appropriate results instead of showing results for the previous input. ( it was giving results an input variable behind )

**Issue Number:**

Fixes #716 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/97829544/225826006-9d54dda3-a849-4cb6-aa2c-9cceac6f02d8.mp4

**If relevant, did you update the documentation?**

Not Relevant.

**Summary**
While searching for users by their first names in the Roles section of talawa admin app, whenever we used to type input, it was showing the relevant results one step afterwards.

for example, If we typed 'f' , it wouldn't show the  users whose names have 'f' in their first name but would only show those results when we type one more letter , say 'fa' - where the results would be shown for users having 'f' in their first names.

It happens because of the useState hook taking time to update. So filtering with event.target.value instead solves this issue.

**Does this PR introduce a breaking change?**

It's not a breaking change but a small change that makes user experience better.

**Other information**

None.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Pranauv-Kumar1803** [comment]
How can I solve linting issue @noman2002 ?

**Comment by Pranauv-Kumar1803** [comment]
hey @palisadoes , Should I add more tests for the 2 codecov errors? Is that the problem ( less code coverage )?

**Comment by palisadoes** [comment]
> hey @palisadoes , Should I add more tests for the 2 codecov errors? Is that the problem ( less code coverage )?

All tests must pass.

File: src/screens/Roles/Roles.tsx [hunk 1]
```diff
@@ -28,6 +29,20 @@ const Roles = () => {
     setComponentLoader(false);
   }, []);
 
+  useEffect(() => {
+    if (searchByName !== '') {
+      refetch({
+        filter: searchByName,
+      });
+    } else {
+      if (count !== 0) {
```
Comment (palisadoes) [inline src/screens/Roles/Roles.tsx:38]: You need to write tests for this

**Review by palisadoes — CHANGES_REQUESTED** [review]

File: src/screens/Roles/Roles.tsx (hunk 1 above)
Comment (Pranauv-Kumar1803) [reply src/screens/Roles/Roles.tsx:38]: That code was added to avoid infinite rendering when the component is first loaded ( since I was using useEffect with searchByName input.

How do I write tests for that? Can I please get some ideas?

Comment (palisadoes) [reply src/screens/Roles/Roles.tsx:38]: Ask the talawa-admin channel on slack

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

The overall code coverage drops below the target threshold of the repository
Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by Pranauv-Kumar1803** [comment]
> 

yeah I'm trying my best to provide more tests.. Sorry for the inconvenience.

**Comment by Pranauv-Kumar1803** [comment]
Hey there @palisadoes , I've given enough tests for the functionality that I implemented in the Roles page and the error that it gives there are for some other parts of it like the rowPerPage( of users ).

Should I work on the tests for that too?

**Comment by palisadoes** [comment]
> Hey there @palisadoes , I've given enough tests for the functionality that I changed in the Roles page and the error that it gives there are for some other parts of it like the rowPerPage( of users ).
> 
> Should I work on the tests for that too?

Yes, we need to make sure the application works as perfectly as possible. Your changes may have created edge case errors in other areas.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please get the coverage back, its dropping.

**Comment by Pranauv-Kumar1803** [comment]
Pls review!

**Comment by noman2002** [comment]
> Pls review!

It is still below the present code coverage. ?

**Comment by Pranauv-Kumar1803** [comment]
> > Pls review!
> 
> It is still below the present code coverage. ?

Yes its because of just 2 lines of code not being covered and they weren't covered in the last commit either..

**Comment by palisadoes** [comment]
Please add tests so that the PR passes. We don't want the quality of our code to decline. It is made better with each PR using this approach.

**Comment by Pranauv-Kumar1803** [comment]
> Please add tests so that the PR passes. We don't want the quality of our code to decline. It is made better with each PR using this approach.

Sorry for the delay but I'm trying my best to cover them.  
I might need some help in covering them because it's like to write tests for a conditional render in the Roles page.

**Comment by kayceeDev** [comment]
@Pranauv-Kumar1803 you can go to this [URL](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/735/blob/src/screens/Roles/Roles.tsx) to see the affected lines of code and then go ahead fixing them.

**Comment by Pranauv-Kumar1803** [comment]
> @Pranauv-Kumar1803 you can go to this [URL](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/735/blob/src/screens/Roles/Roles.tsx) to see the affected lines of code and then go ahead fixing them.

So the thing is these lines weren't covered before also... That's why I'm getting that 1 error... I'm trying to cover it ... I also have asked help ok slack because I've tried lots of tests but it says those lines are partially covered...

**Comment by palisadoes** [comment]
@noman2002 @Kevoniat @Rumone Do you have any suggestions for this?

**Comment by Pranauv-Kumar1803** [comment]
@palisadoes 
I think I've fixed the coverage ! Pls Review !

image

File: package.json [hunk 2]
```diff
@@ -66,7 +66,7 @@
   "scripts": {
     "serve": "react-scripts start",
     "build": "react-scripts build",
-    "test": "react-scripts test",
+    "test": "react-scripts test --coverage",
```
Comment (palisadoes) [inline package.json:69]: Revert this change. It works for our GitHub actions.

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comments

File: package.json (hunk 2 above)
Comment (Pranauv-Kumar1803) [reply package.json]: done! i removed the coverage and pushed

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by Pranauv-Kumar1803** [comment]
Hey @noman2002 @kayceeDev, 
Is there less code coverage because I didn't sync my forked repo with the main talawa admin?

And if I do it, would I lose all my commits?

**Comment by Pranauv-Kumar1803** [comment]
Ignore the last one as I just synced my forked repo with the main talawa admin!

**Comment by Pranauv-Kumar1803** [comment]
Hey @palisadoes sir,
pls review! all checks have passed.

**Review by palisadoes — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]
