### PR TITLE
Delete sample org bug fixed

### LINKED ISSUE #1217: Bug Report: Delete sample org button is not working
**Describe the bug**
Delete Sample org button is not working.

**To Reproduce**

1. Create a sample org.
2. Go to the setting page of the sample org.
3. Try to delete the sample org.
4. You will notice it will not work.

**Expected behavior**
The sample org should be delete by clicking on the delete button.

**Actual behavior**
The delete sample org button does not worked.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/e2111c7c-4338-4dce-b1d2-d69517e9d462

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kanhaiya04**
#1217

**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1217 

**Did you add tests for your changes?**

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/4e20b7a7-10ea-4c2b-8e3b-6c2d026defff

**If relevant, did you update the documentation?**

**Summary**
Delete sample button was not working initially but now in this PR it is fixed.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@kanhaiya04 Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Review by noman2002 — DISMISSED** [review]
Looks fine to me.

**Comment by aashimawadhwa** [comment]
one suggestion can you change the color of the delete modal to green instead of red? please use standard green color used in talawa like other modals to keep the designs consistent @kanhaiya04

**Comment by aashimawadhwa** [comment]
Screenshot 2023-12-31 at 9 45 47 PM
i am pointing towards the header of the modal.

**Comment by kanhaiya04** [comment]
@aashimawadhwa Do I need to change the color of the Confirm Delete button as well?
Or this works
image

**Comment by palisadoes** [comment]
> @aashimawadhwa Do I need to change the color of the Confirm Delete button as well? Or this works image

Please implement this

File: src/components/DeleteOrg/DeleteOrg.tsx [hunk 1]
```diff
@@ -34,11 +34,13 @@ function deleteOrg(): JSX.Element {
       removeSampleOrganization()
         .then(() => {
           toast.success('Successfully deleted sample Organization');
```
Comment (rishav-jha-mech) [inline src/components/DeleteOrg/DeleteOrg.tsx:36]: Make this message multilingual

File: src/components/DeleteOrg/DeleteOrg.test.tsx [hunk 2]
```diff
@@ -114,19 +191,26 @@ describe('Delete Organization Component', () => {
...
-    await waitFor(() => {
-      expect(screen.queryByTestId('orgDeleteModal')).toBeNull();
+    await act(async () => {
+      await new Promise((resolve) => setTimeout(resolve, 1000));
     });
-    expect(window.location).toBeAt('/orgsetting/id=123');
+    screen.getByTestId(/openDeleteModalBtn/i).click();
+    screen.getByTestId(/deleteOrganizationBtn/i).click();
+    await act(async () => {
+      await new Promise((resolve) => setTimeout(resolve, 1000));
```
Comment (rishav-jha-mech) [inline src/components/DeleteOrg/DeleteOrg.test.tsx:200]: Instead of adding the same lines of code everywhere in the tests, you can create an async wait() function in this file, which then you can use over here

File: src/components/DeleteOrg/DeleteOrg.test.tsx [hunk 3]
```diff
@@ -136,15 +212,21 @@ describe('Delete Organization Component', () => {
         </BrowserRouter>
       </MockedProvider>
     );
-    fireEvent.click(screen.getByTestId('openDeleteModalBtn'));
-    expect(screen.getByTestId('orgDeleteModal')).toBeInTheDocument();
-    expect(window.location).toBeAt('/orgsetting/id=123');
+    await wait();
+    screen.getByTestId(/openDeleteModalBtn/i).click();
+    screen.getByTestId(/deleteOrganizationBtn/i).click();
+    await wait();
```
Comment (rishav-jha-mech) [inline src/components/DeleteOrg/DeleteOrg.test.tsx:218]: Pass a duration of 2000ms instead of adding wait twice

**Comment by rishav-jha-mech** [comment]
LGTM

**Review by rishav-jha-mech — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]
