### PR TITLE
Fixed admin card navigation in dashboard

### LINKED ISSUE #1126: Fix in admin card navigation
**Describe the bug**
 currently in talawa dashboard the admin card navigate to all members screen in Talawa Members section.

**To Reproduce**

1. click on manage organization to navigate to dashboard 
2. click on admins card from the dashboard
3. see the issue

**Expected behavior**
 it should navigate to the admin screen in the talawa members section

**Actual behavior**
 it navigates to all members screen in the talawa members section.

**Screenshots**
Screenshot 2023-12-04 at 10 25 12 PM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #1126 

**Snapshots/Videos:**

[www_screencapture_com_2023-12-9_04_32.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/4b40a760-1c65-4159-8eb3-90e4bed3aa79)

**Summary**

Earlier on clicking on the admin card the user was navigated to members section in Talawa Members. Fixed the navigation to direct it to admin section in Talawa Members.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by chandel-aman** [comment]
@aashimawadhwa @noman2002 
Test for OrganizationDashboard.tsx is open #1132 
So do I need to increase the test coverage too?

File: src/screens/OrganizationPeople/OrganizationPeople.tsx [hunk 1]
```diff
@@ -28,9 +29,12 @@ function organizationPeople(): JSX.Element {
 
   document.title = t('title');
 
+  const location = useLocation();
+  const role = location?.state as any;
```
Comment (rishav-jha-mech) [inline src/screens/OrganizationPeople/OrganizationPeople.tsx:33]: Dont use `any` here

**Comment by rishav-jha-mech** [comment]
@chandel-aman you just need to write tests for the changes you have made for now (if required)

**Comment by chandel-aman** [comment]
@rishav-jha-mech The changes made in this PR does not require any extra tests to be written. They are already covered in the existing tests.

File: src/screens/OrganizationPeople/OrganizationPeople.tsx (hunk 1 above)
Comment (chandel-aman) [reply src/screens/OrganizationPeople/OrganizationPeople.tsx]: image
removed the use of `any` defined `interface` instead

**Review by aashimawadhwa — APPROVED** [review]

**Comment by aashimawadhwa** [comment]
LGTM.

**Review by palisadoes — APPROVED** [review]

**Comment by chandel-aman** [comment]
@noman2002 Could please close this issue? The pr for this has been merged.
