### PR TITLE
image upload made functional

### LINKED ISSUE #538: Making Image upload Functional for the Admin-portal
**Describe the bug**

Last Week, a PR to make image uploads functional for the app was made by me on the server side but only applied to `createOrganization` mutation as a precaution against the possibility of breakage of the complete application.

Now with the merge of https://github.com/PalisadoesFoundation/talawa-api/pull/1115 , the image upload is functional on the server-side.

This issue and its subsequent PR will target to make the image uploads function as expected 

Now all that is left is to apply it where needed on the client apps, in the admin portal and talawa mobile app.

**To Reproduce**

1. Try to upload image anywhere except during creating organization
2. The server hangs
3. or Image does not get uploaded

**Expected behavior**

Image should be uploaded and fetched appropriately

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
The server hangs
**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**
This PR will enable the admin-portal to utilize the image uploads functionality properly. 

**Issue Number:**

Fixes #538 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by kb-0311** [comment]
This is still a PR in progress

Also its sister PR for admin portal is this one-

https://github.com/PalisadoesFoundation/talawa-api/pull/1168

**Comment by palisadoes** [comment]
If a review isn't required then just close the PR. We need to reduce the amount of potential work in our queue. Please close this.

**Comment by kb-0311** [comment]
@palisadoes 
Yes Sir,  I get the overwhelming number of issues coming in recently. 

This PR is done , but it is a sister PR for the API one as highlighted by https://github.com/PalisadoesFoundation/talawa-admin/pull/677#issuecomment-1465209991

Only the backend api sister PR tests are remaining. By tomorrow, they will be done (I guess it is a timezone thing)

**Comment by palisadoes** [comment]
Does this one need to be merged first?

**Comment by palisadoes** [comment]
@noman2002 
@Kevoniat 

Please review

**Comment by kb-0311** [comment]
@palisadoes no the api one needs to merged first then this one.

**Comment by Kevoniat** [comment]
@kb-0311  can you look at the failing test?

**Comment by Kevoniat** [comment]
> @palisadoes no the api one needs to merged first then this one.

@palisadoes  do you know who is looking at the API ticket?

**Comment by kb-0311** [comment]
@Kevoniat Yes Sir, I am working on fixing the failed test.

I am the one working on the API PR too https://github.com/PalisadoesFoundation/talawa-api/pull/1168

**Comment by kb-0311** [comment]
@palisadoes @Kevoniat yep done with this PR.

With this PR, the contributors on the admin portal will be able to upload and fetch images appropriately, finally .

**Comment by kb-0311** [comment]
@palisadoes  I am having an exam from 14th to 18th so will be slightly inactive during this time period. 
Now there could be a possibility of bugs existing for this and if they do arise feel free to DM me any time on slack. 

For the mobile app, for that period though, I will be taking external help from a contributor from over there to implement image uploads on mobile app.

**Comment by palisadoes** [comment]
@Kevoniat Please review. We need to get this merged quickly.

**Comment by Kevoniat** [comment]
@kb-0311  the code looks good just fix the Conflicting  files

**Comment by DMills27** [comment]
Any update on the conflicting files that need to be fixed?

**Comment by kb-0311** [comment]
@DMills27 yes fixed the conflicts, Do not merge before the merge of https://github.com/PalisadoesFoundation/talawa-api/pull/1168

**Comment by noman2002** [comment]
@kb-0311 Why the coverage has gone down ?

**Comment by kb-0311** [comment]
@noman2002 Looking into the lower test coverage.

Btw why is the CI test failing even before codecov though all the tests are passed for the 2nd last commit?

**Comment by kb-0311** [comment]
@palisadoes @noman2002  Locally and on the CI too all the tests are passing . Is there a problem with the CI config?
Screenshot from 2023-03-19 12-14-27

**Comment by kb-0311** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4459408349/workflow#L74

maybe could changing that line to `run: yarn test -u` solve the problem?

**Comment by palisadoes** [comment]
But it's only failing for you. Other PRs are passing

**Comment by anshgoyalevil** [comment]
@kb-0311 

Try pushing an empty commit to rerun the tests. Maybe that could solve the problem.

```
git commit --allow-empty -m "Empty commit"
```

**Comment by palisadoes** [comment]
1. I've manually rerun the tests without success. 
2. Maybe the empty commit will work.

**Comment by kb-0311** [comment]
@anshgoyalevil @noman2002 @palisadoes I tried almost everything but I could not find the problem for this one.

**Comment by palisadoes** [comment]
Try fixing the warnings for the files in this PR if they exist.

**Comment by kb-0311** [comment]
@palisadoes the codecov will be low but the tests are passing for the latest commit

For this rare one off thing I would ask you to ignore the lower test coverage for now and I will look at the test coverage later, when @xoldyckk approves the API sister PR you can merge both at the same time no problem

**Review by palisadoes — CHANGES_REQUESTED** [review]
OK. Let me know when this should be reviewed for merging.

**Comment by kb-0311** [comment]
@palisadoes @noman2002  it is ready to be reviewed. The codecov difference is only -0.07 percent and that is unrelated to the changes made in this PR

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
@kb-0311 Please confirm if this is ready for merging.

**Comment by kb-0311** [comment]
@palisadoes Sure it is ready for merging.

**Review by palisadoes — APPROVED** [review]

File: src/components/UserUpdate/UserUpdate.tsx [hunk 1]
```diff
@@ -20,6 +23,10 @@ const UserUpdate: React.FC<UserUpdateProps> = ({ id }): JSX.Element => {
     firstName: '',
     lastName: '',
     email: '',
+    password: '',
+    applangcode: '',
+    selectedOption: '',
```
Comment (anshgoyalevil) [inline src/components/UserUpdate/UserUpdate.tsx:28]: @kb-0311 
These fields were removed previously. There is a separate component for password update.

Also, the applangcode and selectedOption are redundant. Since, they are stored while signing up.

Due to the changes in this file, the update user page is not working for now.

Comment (kb-0311) [reply src/components/UserUpdate/UserUpdate.tsx:28]: @anshgoyalevil I was not aware of this, maybe the changes happened because of git conflicts resolution.

Comment (anshgoyalevil) [reply src/components/UserUpdate/UserUpdate.tsx:28]: @kb-0311 Should we proceed with a new issue, or a new PR linking this issue?

Comment (kb-0311) [reply src/components/UserUpdate/UserUpdate.tsx:28]: @anshgoyalevil Yeah sure you can create the issue and fix it
