### PR TITLE
Fix to the issue #585

### LINKED ISSUE #585: Bug Report
On the talawa admin portal the password field shows that the password should be 8 characters long. When user types in the password and it satisfies the 8 character long criteria then that should disappear which isn't happening now.

* The 8 character long criteria for password should disappear when the user types a password which satisfies it because it leaves a sense of confusion.

image

### PR DESCRIPTION
**Pull request by arushi2715**
#**What kind of change does this PR introduce?**

This PR introduces a bug fix.

**Issue Number:**

Fixes #585 

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No

**Summary**

Earlier, the password field showed a warning even when it satisfied the criteria which leaves a sense of confusion for the user. Fixing this gives a clear idea to the user.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by arushi2715** [comment]
Hey @palisadoes can you look into this once again please?

**Comment by palisadoes** [comment]
After reviewing this again, the text is informative to a new user registering. Removing it would create more chances for a poor user experience. 

Closing. Don't be discouraged. Please search for other areas of improvement.

**Comment by arushi2715** [comment]
@palisadoes the issue with this is that even if the password satisfies the criteria i.e. is 8 character long even then it shows the check message. What I wanted to do here was to remove the text "password should be 8 character long" if the password entered by user is 8 character long.

**Comment by arushi2715** [comment]
@palisadoes @xoldyckk can you look into this?

**Comment by xoldyckk** [comment]
@palisadoes This fix was for a good UI experience. The error message that `the entered password is not at least 8 characters long` was being displayed even when the user had already entered a password with more than 8 characters. 

The fix is to automatically remove that message if the entered password is greater than 8 characters.

@arushi2715 You may continue.

**Comment by arushi2715** [comment]
Sure @xoldyckk I'll fix it asap.
Thanks.

**Comment by arushi2715** [comment]
@xoldyckk @palisadoes I have fixed this issue. Can you please look into this once.

Now when the password id less than 8 characters it shows the usual error warning as shown in below attachment.

image

If the password length is greater than 8 character the warning is not shown.

image

File: src/screens/LoginPage/LoginPage.tsx [hunk 1]
```diff
@@ -334,7 +338,11 @@ function LoginPage(): JSX.Element {
                         });
                       }}
                     />
-                    <span>{t('atleast_8_char_long')}</span>
+                    {signformState.signPassword.length < 8 ? (
+                      <span>{t('atleast_8_char_long')}</span>
+                    ) : (
+                      <span>{''}</span>
```
Comment (xoldyckk) [inline src/screens/LoginPage/LoginPage.tsx:344]: I believe a better syntax to do this would be 

```tsx
{signformState.signPassword.length < 8 && <span>{t('atleast_8_char_long')}</span>}
```

File: src/screens/LoginPage/LoginPage.tsx [hunk 2]
```diff
@@ -156,6 +158,8 @@ function LoginPage(): JSX.Element {
 
     const isVerified = await verifyRecaptcha(recaptchaToken);
 
+    // const isVerified = true;
```
Comment (xoldyckk) [inline src/screens/LoginPage/LoginPage.tsx:161]: Remove this comment.

File: src/screens/LoginPage/LoginPage.tsx [hunk 3]
```diff
@@ -95,6 +95,8 @@ function LoginPage(): JSX.Element {
...
```
Comment (xoldyckk) [inline src/screens/LoginPage/LoginPage.tsx:98]: Remove this comment.

**Review by xoldyckk — CHANGES_REQUESTED** [review]

**Comment by arushi2715** [comment]
Hey @xoldyckk I made the necessary changes. Can you please review them once.

**Comment by xoldyckk** [comment]
> Hey @xoldyckk I made the necessary changes. Can you please review them once.

You see those comments I made? When you do the things I asked in those comments, you should click on `resolve conversation`. Remember to do this from now on.

**Review by xoldyckk — DISMISSED** [review]

**Comment by arushi2715** [comment]
Sure @xoldyckk I'll keep this in mind.

**Comment by xoldyckk** [comment]
@arushi2715 One more thing. What is the initial UI behaviour when client first lands on sign up page? It wouldn't be good to just continously display that error message. It only makes sense when the client has altered the password field at least once.

A simple approach for this would be making default value of password null. If client enters something that password state will get rewritten to a string. Now, even if client clears their password, the password state will have an empty string `""` in state instead of null value.

So, in your check you can check that if password value is null don't display the message, but if it is an empty string display it. This will make sure that client doesn't see the password is too short error right when they first land on that page.

**Comment by arushi2715** [comment]
@xoldyckk yeah this makes sense and it will be a better approach to deal with password error.
I'll make the changes.

**Comment by xoldyckk** [comment]
> @xoldyckk yeah this makes sense and it will be a better approach to deal with password error. I'll make the changes.

Make sure you leave useful comments to let others understand why you did it this way. Don't worry about comments cluttering the codebase. Comments are good.

**Comment by arushi2715** [comment]
@xoldyckk can we not make a state regarding if our input is focused or not and then we can update the state when that text field is clicked on. So, basically we won't display the message until our text field is not focused but as soon as it is clicked we will display it? Do you think this will be a better approach for handeling this?

**Comment by xoldyckk** [comment]
> @xoldyckk can we not make a state regarding if our input is focused or not and then we can update the state when that text field is clicked on. So, basically we won't display the message until our text field is not focused but as soon as it is clicked we will display it? Do you think this will be a better approach for handelling this?

Both are viable approaches. Just think about what is easier and do that.

**Comment by arushi2715** [comment]
@xoldyckk can you please review it once?

**Comment by xoldyckk** [comment]
@arushi2715 Can you record a short video?

**Comment by arushi2715** [comment]
Hey @xoldyckk you can check the attachment linked below.

https://user-images.githubusercontent.com/78142604/224503385-76112304-4f7f-4b32-b808-a5efafdb4830.mp4

**Comment by xoldyckk** [comment]
@arushi2715 Looks good. You also have to write the corresponding tests for testing UI behaviour for some of the steps I mentioned.

**Comment by palisadoes** [comment]
> @arushi2715 Looks good. You also have to write the corresponding tests for testing UI behaviour for some of the steps I mentioned.

If the tests are required, why approve it?

**Comment by arushi2715** [comment]
@xoldyckk can you please explain a bit? Also, should I do this it in this PR only or open a new issue for the same?

**Comment by xoldyckk** [comment]
> @xoldyckk can you please explain a bit? Also, should I do this it in this PR only or open a new issue for the same?

You have to test that when `focus` and `blur` events happen for password input field, the warning is displayed according to the `<8` logic. You have to attach the tests within this PR. Whenever you fix an issue, or add a new feature the unit tests need to be written along as well.

**Comment by arushi2715** [comment]
Hey @xoldyckk thanks for explaining.
Sure, I'll keep this in mind and will add the test cases for this asap.

**Comment by arushi2715** [comment]
@xoldyckk can you check it once please?

**Comment by xoldyckk** [comment]
@arushi2715 You're using the error message to query for its html element. I think that's a bad practice for something which can easily change. Instead you should make use of some test id for the element which holds that message. Change that.

Everything else looks fine.

**Comment by arushi2715** [comment]
@xoldyckk changed it. Can you review it once?

**Review by xoldyckk — APPROVED** [review]
Looks good. Nice job.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please lint the code so that the tests can pass.

**Comment by arushi2715** [comment]
@palisadoes can you please check it once?

**Comment by arushi2715** [comment]
@xoldyckk @palisadoes one test case is failing in ` src/screens/OrganizationEvents/OrganizationEvents.test.tsx` due to which the code coverage is not being shown.

**Review by palisadoes — APPROVED** [review]
