### PR TITLE
fix: updated overflowing text of post admin

### LINKED ISSUE #4576: Bug Report: Text is overflowing on the post
**Describe the bug**
Text is overflowing on the post 

**Expected behavior**
It should not overflow. 

**Actual behavior**

Image

**Screenshots**

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by VanshikaSabharwal**
**What kind of change does this PR introduce?**
 a bugfix

**Issue Number:**

Fixes #4576

**Snapshots/Videos:**
https://github.com/user-attachments/assets/a3d2f72f-ec66-419c-9eab-ec3ba6418040

**If relevant, did you update the documentation?**

**Summary**
This PR fixes the caption text overflow issue in the organizational post cards (OrgPostCard component).
Previously, long captions would overflow or be cut off abruptly. The fix introduces an expandable text section similar to Instagram’s “View more / View less” pattern.

**Does this PR introduce a breaking change?**
No

### CodeRabbit AI Review
- [X] I have reviewed and addressed all critical issues flagged by CodeRabbit AI
- [X] I have implemented or provided justification for each non-critical suggestion
- [X] I have documented my reasoning in the PR comments where CodeRabbit AI suggestions were not implemented

### Test Coverage
- [X] I have written tests for all new changes/features
- [X] I have verified that test coverage meets or exceeds 95%
- [X] I have run the test suite locally and all tests pass

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Release Notes

* **New Features**
  * Added expandable caption display for organization posts with "Show more/Show less" toggle to manage long captions.

* **UI/UX Improvements**
  * Enhanced post card styling with improved visual presentation, including refined borders, shadows, and dynamic height adjustment based on content.

### CODE REVIEW

File: src/components/OrgPostCard/OrgPostCard.tsx [hunk 1]
```diff
@@ -365,12 +380,60 @@ export default function OrgPostCard({
               />
             )}
 
-            <Card.Body>
+            <Card.Body
+              style={{
+                minHeight: '120px',
+                transition: 'all 0.4s ease',
```
Comment (palisadoes) [inline src/components/OrgPostCard/OrgPostCard.tsx]: Use CSS here. Hard coding values will cause issues in future.
- src/style/app-fixed.module.css

File: src/components/OrgPostCard/OrgPostCard.tsx [hunk 2]
```diff
@@ -365,12 +380,60 @@ export default function OrgPostCard({
...
               {isPinned && (
                 <PushPin color="success" fontSize="large" className="fs-5" />
               )}
               <Card.Title className={styles.titleOrgPostCard}>
-                {post.caption}
+                <div
+                  ref={captionRef}
+                  style={{
+                    lineHeight: '1.6em',
+                    whiteSpace: 'pre-wrap',
```
Comment (palisadoes) [inline src/components/OrgPostCard/OrgPostCard.tsx]: Use CSS from src/style/app-fixed.module.css .

File: src/components/OrgPostCard/OrgPostCard.tsx [hunk 3]
```diff
@@ -365,12 +380,60 @@ export default function OrgPostCard({
...
+                </div>
+
+                {isLong && (
+                  <button
+                    onClick={toggleExpand}
+                    style={{
+                      background: 'none',
+                      border: 'none',
+                      color: '#007bff',
+                      cursor: 'pointer',
```
Comment (palisadoes) [inline src/components/OrgPostCard/OrgPostCard.tsx]: Use CSS for this entire section
- src/style/app-fixed.module.css

**Comment by palisadoes** [comment]
@coderabbitai full review

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please ensure Code Rabbit approves your changes.
2. There are some critical ones.

**Comment by VanshikaSabharwal** [comment]
@coderabbit approve

**Review by palisadoes — APPROVED** [review]
