### PR TITLE
Fixed Org Dashboard Error

### LINKED ISSUE #872: Organization Dashboard - Fix Console Error
**Describe the bug**

**To Reproduce**

1. Run Talawa Admin and Log In
2. Open the console
3. On the OrgList page, click the `Manage` button for any organization
4. It should display a `TypeError` in the console

**Expected behavior**
There should not be any error

**Actual behavior**
The console displayed the following error -

```
Uncaught TypeError: Cannot read properties of undefined (reading 'organizations')
```

**Screenshots**

Screenshot 2023-04-13 at 1 28 15 AM

**Additional details**

NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by prathamesh-mutkure**
**What kind of change does this PR introduce?**

Bug Fix

**Issue Number:**

Fixes #872 

**Did you add tests for your changes?**

Not Required 

**Snapshots/Videos:**

No errors or warnings on console -

Screenshot 2023-04-13 at 2 32 23 AM

**If relevant, did you update the documentation?**

Not Relevant

**Summary**

- The `data` being undefined caused a `TypeError`
- Fixed this with a simple conditional check using the Null Safety operator
- Also added back the `logo512.png` image which was deleted in the last commit 
- As it caused the manifest to give warnings

**Does this PR introduce a breaking change?**

No

**Other information**

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by Kevoniat — APPROVED** [review]

File: src/screens/OrganizationDashboard/OrganizationDashboard.tsx [hunk 1]
```diff
@@ -94,24 +97,20 @@ function OrganizationDashboard(): JSX.Element {
             <div className={styles.sidebarsticky}>
               <h6 className={styles.titlename}>{t('about')}</h6>
               <p className={styles.description}>
-                {data.organizations[0].description}
+                {data?.organizations[0].description}
               </p>
               <p className={styles.toporgloc}>
-                {t('location')} : {data.organizations[0].location}
+                {t('location')} : {data?.organizations[0].location}
```
Comment (Rumone) [inline src/screens/OrganizationDashboard/OrganizationDashboard.tsx:103]: This condition suggests that there instances where data is `null` or `undefined`. That said, what will you display if that happens.

Comment (prathamesh-mutkure) [reply src/screens/OrganizationDashboard/OrganizationDashboard.tsx:103]: Hi @Rumone, actually the `data` can be `undefined` only when the `id` is invalid which case is already being handled by the `error` field.

The problem here is asynchronous state changes - 

- We fetch the Organization, data is initially `undefined` while `loading` becomes true
- Once the data is loaded, `loading` becomes false and we show the `data` which now has a value
- And in case something goes wrong, `error` is set to the error, and `data` is still `undefined`
- We are handling the error case before accessing `data`

Thus, theoretically `data` cannot be `undefined` unless there's an error from the backend which we have already handled using `error`  before accessing `data`

The problem is the value of `data` is not immediately set after `loading` becomes false

The conditional check is only to wait for the value to be updated by Apollo Client

I don't think we need to display it in this condition

Comment (prathamesh-mutkure) [reply src/screens/OrganizationDashboard/OrganizationDashboard.tsx:103]: @Rumone can we resolve this?

**Comment by prathamesh-mutkure** [comment]
@Kevoniat I've merged the recent changes, can you please approve this again?

**Review by ttaylor92 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]
