### PR TITLE
fixed User login requires refresh to fetch data

### LINKED ISSUE #1498: Bug Report: User login requires refresh to fetch data
**Describe the bug**
After logging as user we need to refresh the page to fetch the data.

**To Reproduce**

1. Login as user
2. You will notice no data is present, showing undefined.

**Expected behavior**
Data of the user should be fetched after successful login.

**Actual behavior**
Data is not fetched properly after the login, need to refresh to the page to get the data.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/179b8da7-6ba7-4624-bac3-a4108acd9f41

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kanhaiya04**
**What kind of change does this PR introduce?**

Refactoring

**Issue Number:**

Fixes #1498 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Modified the ApolloClient to use setContext function to update the header dynamically as the value changes in local storage.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
can you attach the video of how it is working now? @kanhaiya04

**Comment by kanhaiya04** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/1d46c301-8425-4395-b178-193b9d5f6872

**Review by beingnoble03 — DISMISSED** [review]
this bug looks legit. changes lgtm, thanks @kanhaiya04

**Comment by beingnoble03** [comment]
Actually coming back here again,
@kanhaiya04 I think we need to update the items in the `localStorage` after fetching the data from `CHECK_AUTH` query.

**Comment by palisadoes** [comment]
@kanhaiya04 

An update would be very helpful.

1. The port `4321` only solves part of the problem. 
2. I've had cases where the Admin Portal fails when testing PR code and the constant refreshing starts all over again. 
3. I have to use a separate browser to test all Admin PRs now.

**Comment by kanhaiya04** [comment]
@beingnoble03 @aashimawadhwa I've encountered some additional bugs which I was trying understand.

I'm curious about why `checkAuth` is persistently returning the information of the previously logged-in user even after passing the token of a new user in the headers. This issue arises when I use `history.push('/user')` instead of `window.location.replace('/user')` in the logout function of the `user screen`.

Does `checkAuth` require a `hard` reload to fetch new data, or is there a specific reason it keeps returning the same value?

If I stick with `window.location.replace('/user')`, when a user logs out from the Admin and logs in on the User screen, `checkAuth` returns the data of the Admin, not the user. Is this happens because the logout function of the Admin screen uses `history.push`?

Why `checkAuth` is behaving like this??

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the conflicting files.

**Comment by kanhaiya04** [comment]
I will address the conflicting files in the next few days, as I am currently occupied with exams.

**Comment by palisadoes** [comment]
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

**Comment by noman2002** [comment]
@kanhaiya04 Any update on this ?

**Comment by kanhaiya04** [comment]
I have fixed the conflicting files.

File: src/components/UserPortal/UserNavbar/UserNavbar.tsx [hunk 1]
```diff
@@ -20,24 +20,30 @@ function userNavbar(): JSX.Element {
...
     cookies.get('i18next') || 'en',
   );
 
+  const [userName, setUserName] = React.useState('');
+
+  const { data } = useQuery(CHECK_AUTH);
+
+  React.useEffect(() => {
+    if (data) {
+      setUserName(`${data.checkAuth.firstName} ${data.checkAuth.lastName}`);
```
Comment (beingnoble03) [inline src/components/UserPortal/UserNavbar/UserNavbar.tsx:36]: Shouldn't we set this in `localStorage` instead of react state?

**Review by beingnoble03 — COMMENTED** [review]
I think we should set the `userName` in the localStorage, and then use getItem?

File: src/components/UserPortal/UserNavbar/UserNavbar.tsx (hunk 1 above)
Comment (palisadoes) [reply src/components/UserPortal/UserNavbar/UserNavbar.tsx:36]: We had issues with using `localStorage` in the past. Our PR workflows will flag its use and fail because of this.

Comment (kanhaiya04) [reply src/components/UserPortal/UserNavbar/UserNavbar.tsx:36]: I'm trying to fix this but facing the [above](https://github.com/PalisadoesFoundation/talawa-admin/pull/1533#issuecomment-1930625459) mentioned issue.

**Comment by kanhaiya04** [comment]
@beingnoble03 @noman2002 @aashimawadhwa  @palisadoes Seeking assistance: Is the **checkAuth** data **cached** somewhere? Even when a user logs out and a new user logs in, **checkAuth** returns the previous value **without making an API call** to the backend. Consequently, **false** values are being set in the **local storage.**

**Comment by kanhaiya04** [comment]
@beingnoble03 @noman2002 @aashimawadhwa @palisadoes I have fixed the issue.
I issue was with the no setting the `fetchPolicy to network-only`

```js
const { data } = useQuery(CHECK_AUTH, { fetchPolicy: 'network-only' });
```

Without setting the fetchPolicy to 'network-only', `checkAuth` returns the cached previously logged in user data, as Apollo Client automatically caches query results locally when it fetches them from the server. This caching mechanism results in faster executions of the same query later.
https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy

**Review by beingnoble03 — APPROVED** [review]
lgtm. thanks @kanhaiya04 for the explanation.

**Review by palisadoes — APPROVED** [review]
