### PR TITLE
fix user update 

### LINKED ISSUE #869: Bug Report: update user details not working
**Describe the bug**

The Update user section in the settings do not update the details and still gives success toast 
**To Reproduce**

1. Login as a admin or superadmin
2. go to user settings
3. Update the firstName, LastName, email
4. Hit Save changes
5. "Successfully updated" Toast appears
6. See user details again, (they are not updated)

**Expected behavior**
This should actually update the details 

**Actual behavior**
Functionality not working

**Screenshots**
N/A
**Additional details**
N/a

### PR DESCRIPTION
**Pull request by adi-uchiha**
**What kind of change does this PR introduce?**
This is a minor change in the user update field in the settings page. 
Now, The user can update firstname, lastname, email and image successfully 

**Issue Number:**
Fixes #869 

**Did you add tests for your changes?**
N/A

**Does this PR introduce a breaking change?**
NO

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
@adi-uchiha 

Please remove the ```Default Language``` and ```User Type``` fields also. They are redundant.

**Comment by anshgoyalevil** [comment]
@adi-uchiha 

In that case, you can keep Default Language Field. Since User Type is still redundant.

**Comment by adi-uchiha** [comment]
Will fix the tests soon!

**Review by ttaylor92 — APPROVED** [review]

**Comment by palisadoes** [comment]
Why are you modifying the calendar functionality if the original issue is to fix user updates?

**Comment by adi-uchiha** [comment]
My bad, those commits were for another issue that I am working on. I forgot to push them on a seperate branch that's why they are appearing here. I will be fixing this in few hours as I am in college right now  @palisadoes

**Comment by adi-uchiha** [comment]
@palisadoes You can merge now

File: src/components/UserUpdate/UserUpdate.tsx [hunk 1]
```diff
@@ -182,41 +184,6 @@ const UserUpdate: React.FC<UserUpdateProps> = ({ id }): JSX.Element => {
                 </select>
               </label>
             </div>
-            <div>
-              <label>
-                {t('userType')}
-                <div className={styles.radio_buttons}>
-                  <input
-                    type="radio"
-                    id="admin"
```
Comment (palisadoes) [inline src/components/UserUpdate/UserUpdate.tsx:191]: Why have you removed the functionality to adjust the user type?

File: src/components/UserUpdate/UserUpdate.tsx [hunk 2]
```diff
@@ -182,41 +184,6 @@ const UserUpdate: React.FC<UserUpdateProps> = ({ id }): JSX.Element => {
...
-                        ...formState,
-                        selectedOption: e.target.value,
-                      });
-                    }}
-                  />
-                  <label htmlFor="admin">{t('admin')}</label>
-                  <input
-                    type="radio"
-                    id="superadmin"
-                    value="selectsuperadmin"
```
Comment (palisadoes) [inline src/components/UserUpdate/UserUpdate.tsx:206]: Why have you removed the functionality to adjust the user type?

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please respond to the questions.

File: src/components/UserUpdate/UserUpdate.tsx (hunk 2 above)
Comment (adi-uchiha) [reply src/components/UserUpdate/UserUpdate.tsx:206]: @palisadoes  Because @anshgoyalevil pointed to remove that


> In that case, you can keep Default Language Field. Since User Type is still redundant. [(Comment Link)](url)

 also we have a separate page for managing user roles and change them.

Comment (adi-uchiha) [reply src/components/UserUpdate/UserUpdate.tsx:206]: Also the userUpdateApi do not support this
