### PR TITLE
Fix/codecov coverage comparison

### LINKED ISSUE #4489: Talawa-Admin: 5X Testing Speed Improvement
## This is going to require an experienced developer as it is a complex task.

---

**Describe the bug**

1. Our Admin testing process takes too long.
2. We need to find a way to improve its speed without changing the testing package. We have tried various packages in the past with only nominal improvements.

**Expected behavior**

1. At least a 5X improvement in speed
2. Consider running tests in parallel using dynamically generated random test values
3. All tests must pass and be valid
4. The overall test code coverage of the repo and individual code files must be maintained or improved.

**Additional details**

1. This may require a phased approach with existing files gradually migrated to the new methodology.
2. Explain your approach in the comments below before assignment to provide assurances that you will be able to complete the task.

**Related Issues**

- https://github.com/PalisadoesFoundation/talawa-api/issues/3639
- https://github.com/PalisadoesFoundation/talawa-admin/issues/4489

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ansingh0305**
**What kind of change does this PR introduce?**

Fix (CI/CD Configuration)

**Issue Number:**

Fixes #4489 

**Snapshots/Videos:**

N/A (CI Workflow change)

**If relevant, did you update the documentation?**

N/A

**Summary**

This PR fixes an issue where Codecov reports were showing "Everything is accounted for! No changes detected" instead of actual coverage changes.

Changes include:
1. **Explicit Base Branch Fetch**: Fetches `origin/develop` to ensure git history is available for comparison.
2. **Merge Base Calculation**: Calculates the exact merge-base commit SHA.
3. **Explicit Commit Parent**: Passes the merge-base SHA to Codecov via `commit_parent` to force correct comparison.
4. **Diagnostics**: Adds steps to validate `nyc` merge integrity and `lcov.info` structure to help debug future coverage issues.

**Does this PR introduce a breaking change?**

No

### CodeRabbit AI Review
- [ ] I have reviewed and addressed all critical issues flagged by CodeRabbit AI
- [ ] I have implemented or provided justification for each non-critical suggestion
- [ ] I have documented my reasoning in the PR comments where CodeRabbit AI suggestions were not implemented

### Test Coverage
- [ ] I have written tests for all new changes/features
- [ ] I have verified that test coverage meets or exceeds 95%
- [ ] I have run the test suite locally and all tests pass

**Other information**

This change is critical for accurately tracking test coverage in pull requests.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

* **Chores**
  * Improved CI coverage workflow: added base-commit detection and merge-base output, stronger merged-coverage validation, explicit lcov generation and analysis (path checks and file counts), per-shard artifact cleanup, and stricter upload conditions for more reliable coverage reporting.  
* **New Features**
  * Date formatting now returns "Uncovered" for the special uncovered-test placeholder instead of attempting to parse it.  
* **Tests**
  * Disabled the specific ordinal-suffix date test for the "st" case.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/utils/dateFormatter.ts [hunk 1]
```diff
@@ -31,3 +31,19 @@ export function formatDate(dateString: string): string {
...
+  if (isNaN(date.getTime())) {
+    throw new Error('Invalid date string provided');
+  }
+
+  return date.toLocaleTimeString('en-US', {
+    hour: 'numeric',
+    minute: '2-digit',
+    hour12: true,
+  });
+}
```
[the remark this answers is not in the document]
Comment (Ansingh0305) [reply src/utils/dateFormatter.ts]: I am testing something and for that i have to make some coverage changes that is why i have included a new component i will be removing that and reverting this file after i am done

**Comment by Ansingh0305** [comment]
@coderabbitai from what i found out the codecov's auto checker feature was taking the wrong branch as the base branch which was causing it to give wrong values, i have made some changes for to take the correct commit as the base commit please check the changes and let me know if this is fine and would work correctly. It worked correctly in a recent commit that i did, just comfirm it and if everything is fine and there are no issues including the trivial ones, then approve of this pull request.

**Comment by palisadoes** [comment]
@Ansingh0305 

Please validate this with a test file in this PR

**Comment by Ansingh0305** [comment]
> @Ansingh0305
> 
> Please validate this with a test file in this PR

@palisadoes 

I already did it, it worked and showed the correct drop in coverage as it should.
After making sure it worked i reverted the change.

File: .prettierignore [hunk 2]
```diff
@@ -4,3 +4,4 @@ src/components/CheckIn/tagTemplate.ts
 vitest.config.ts
 docs/pnpm-lock.yaml
 pnpm-lock.yaml
+docs/docusaurus.config.ts
```
Comment (palisadoes) [inline .prettierignore]: Please remove this. It has been fixed already.

Comment (Ansingh0305) [reply .prettierignore]: Alright.

**Comment by palisadoes** [comment]
@coderabbitai full review and reevaluate all resolved items and include the following points:

1. Validate whether any updated test files cover all use cases, are valid and that all lines of code are covered with tests.
1. Analyze any submitted code files and evaluate whether there are any unit tests that may be required, and if so identify the lines that are missing tests.
1. Identify any unnecessary files that have been submitted and ask that they be excluded.
1. If the PR requires any changes, even trivial ones, then give your review a “requested changes” status. If no changes are required then give the PR an “approved” status.

**Comment by Ansingh0305** [comment]
I modified it and then reverted it that is probably why its saying that i did not modify any other file
