### PR TITLE
#3174 Action Item Pages Violate The Figma Style Guide

### LINKED ISSUE #3174: Figma: Action Item Pages Violate The Figma Style Guide
## Post a video of your work in the PR

**Describe the bug**

1. Action Item Pages Violate The Figma Style Guide

**To Reproduce**

1. Style Related
    1. Login to the app
    2. Select an organization
    3. Select action items
    4. The figma guide is not followed fully

**Expected behavior**

1. The screens shown must conform to Figma
3. This must apply to the following were relevant:
    1. Users
    2. Admins
    5. SuperAdmins
1. Tests must be written to ensure this does not happen again
2. The CSS must be consolidated into this file using variables wherever possible
    1. `src/style/app.module.css`

**Other**
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
1. When in doubt about colors, take cues from other similar elements in this file and the PR mentioned in the issue.
    1. https://www.figma.com/design/dmKt00m9GVSeA1nebnkxql/Untitled?node-id=0-1&node-type=canvas&t=TPzfh1DE9IxjzsEe-0
1. The desired single CSS file is:
    1. `src/style/app.module.css`
        1. Convert all code files to use this file.
        1. Delete all CSS files in this code path and below mentioned in the title. The `src/style/app.module.css` file must be the only source of CSS
1. Use no CSS in:
    1. `assets/css/app.css`    
1. Use variable names that describe the function of the color and not the color itself. This will help with future attempts to having Dark Mode.
    1. For example `--search-button-bg` is much better than `--light-blue` 
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/3296
1. When refactoring modals, please refer to this PR that has created a standardized design patter for them.
   1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2984
1. Remove all references to HTML color codes in the files you edit except in `src/style/app.module.css`
1. Buttons, and dropdowns must only have shadows when there is a mouse hover. Their color must not change
1. Search boxes must only have shadows when selected

**Actual behavior**
- See screenshots

**Screenshots**

1. Main Screen
    image
1. Adding items
    image
1. After adding items
    image

**Additional details**

There is no figma page for this. Take design cues from this page

1. Background color guide - Use these instead of those that may be different in sample pages below. Our Figma design is not consistent
    image
1. Manage action items
    image
1. Guide
    image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pranavnathe**
**What kind of change does this PR introduce?**

This PR updates the styling of the Action Items page to align with the Figma design specifications.

**Issue Number:**

Fixes #3174 

**Snapshots/Videos:**

https://github.com/user-attachments/assets/96e0c702-dfa0-4b6d-afa1-f44d5fe6e061

**If relevant, did you update the documentation?**

**Summary**

This PR resolves issues related to the design mismatch and ensures the page adheres to the design guidelines.

**Does this PR introduce a breaking change?**

No

### CodeRabbit AI Review
- [ ] I have reviewed and addressed all critical issues flagged by CodeRabbit AI
- [ ] I have implemented or provided justification for each non-critical suggestion
- [ ] I have documented my reasoning in the PR comments where CodeRabbit AI suggestions were not implemented

### Test Coverage
- [ ] I have written tests for all new changes/features
- [ ] I have verified that test coverage meets or exceeds 95%
- [ ] I have run the test suite locally and all tests pass

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Release Notes

- **Style Updates**
  - Updated primary theme color to use a dynamic value from CSS variables.
  - Introduced new `.closeButton` class for consistent modal button styling.
  - Added CSS variables for improved flexibility in button and checkbox styling.
  - Shifted DataGrid styling from inline to CSS module-based styling.
  - Enhanced hover and focus styles for buttons and checkboxes, including drop shadow effects.

- **Bug Fixes**
  - Added robust error handling for root container initialization.
  - Corrected invalid background color values in UI components.

- **Chores**
  - Standardized close button class names across modals.
  - Adjusted test case timing expectations for response delays.

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ import '../src/assets/css/scrollStyles.css';
 const theme = createTheme({
   palette: {
     primary: {
-      main: '#31bb6b',
+      main: '#1778F2',
```
Comment (palisadoes) [inline src/index.tsx:41]: No embedded HTML color codes. Move this to the `app.module.css` file.

File: src/screens/OrganizationActionItems/OrganizationActionItems.tsx [hunk 2]
```diff
@@ -468,20 +468,20 @@ function organizationActionItems(): JSX.Element {
         }}
         sx={{
           borderRadius: '20px',
-          backgroundColor: 'EAEBEF)',
+          backgroundColor: 'FFFFFF)',
           '& .MuiDataGrid-row': {
-            backgroundColor: '#eff1f7',
+            backgroundColor: '#FFFFFF',
```
Comment (palisadoes) [inline src/screens/OrganizationActionItems/OrganizationActionItems.tsx:473]: No embedded HTML color codes. Move this to the `app.module.css` file.

File: src/screens/OrganizationActionItems/OrganizationActionItems.tsx [hunk 3]
```diff
@@ -468,20 +468,20 @@ function organizationActionItems(): JSX.Element {
...
             },
           },
           '& .MuiDataGrid-row:hover': {
-            backgroundColor: '#EAEBEF',
+            backgroundColor: '#FFFFFF',
             boxShadow: '0 0 0 1px rgba(0, 0, 0, 0.1)',
           },
           '& .MuiDataGrid-row.Mui-hovered': {
-            backgroundColor: '#EAEBEF',
+            backgroundColor: '#FFFFFF',
```
Comment (palisadoes) [inline src/screens/OrganizationActionItems/OrganizationActionItems.tsx:484]: No embedded HTML color codes. Move this to the `app.module.css` file.

File: src/screens/OrganizationActionItems/OrganizationActionItems.tsx [hunk 4]
```diff
@@ -468,20 +468,20 @@ function organizationActionItems(): JSX.Element {
...
-            backgroundColor: '#eff1f7',
+            backgroundColor: '#FFFFFF',
             '&:focus-within': {
               // outline: '2px solid #000',
               outlineOffset: '-2px',
             },
           },
           '& .MuiDataGrid-row:hover': {
-            backgroundColor: '#EAEBEF',
+            backgroundColor: '#FFFFFF',
```
Comment (palisadoes) [inline src/screens/OrganizationActionItems/OrganizationActionItems.tsx:480]: No embedded HTML color codes. Move this to the `app.module.css` file.

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. When you hover over the icons in the options column, the icons change color. There should only be a shadow.
2. When you click on the icons, they turn green. There should be no color change.
3. At the end of the video the unchecked box has a green border. There should be none

**Review by palisadoes — CHANGES_REQUESTED** [review]
The delete trash can icon is smaller than the other blue ones in the options column. It must be the same size

**Comment by pranavnathe** [comment]
> The delete trash can icon is smaller than the other blue ones in the options column. It must be the same size

Action Items icon size fix
Fixed the icon size.

**Comment by pranavnathe** [comment]
> 1. When you hover over the icons in the options column, the icons change color. There should only be a shadow.
> 2. When you click on the icons, they turn green. There should be no color change.
> 3. At the end of the video the unchecked box has a green border. There should be none


https://github.com/user-attachments/assets/20609212-7b9e-473b-992a-28d508967642

File: src/style/app.module.css [hunk 5]
```diff
@@ -604,16 +614,16 @@
...
+  border-color: var(--search-button-border) !important;
   color: var(--brown-color);
   margin-right: 0.5rem;
   border-radius: 0.25rem;
 }
 
 .infoButton:hover {
-  background-color: var(--light-blue-color);
-  border-color: var(--search-button-border);
+  color: var(--brown-color) !important;
```
Comment (palisadoes) [inline src/style/app.module.css:625]: Use a variable name not the hex/rgba code (Use 8 digit HTML codes for transparency if necessary). Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.  
- For example `--search-button-bg` is much better than `--light-blue`

File: src/index.tsx [hunk 6]
```diff
@@ -38,7 +38,9 @@ import '../src/assets/css/scrollStyles.css';
 const theme = createTheme({
   palette: {
     primary: {
-      main: '#31bb6b',
+      main: getComputedStyle(document.documentElement)
+        .getPropertyValue('--blue-primary')
```
Comment (palisadoes) [inline src/index.tsx:42]: Use a variable name not the hex/rgba code (Use 8 digit HTML codes for transparency if necessary). Ensure that the variable name you choose describes the function of the color and not the color itself. This will help with future attempts to having Dark Mode.  
- For example `--search-button-bg` is much better than `--light-blue`  

Use values from `app.module.css`

**Comment by pranavnathe** [comment]
https://github.com/user-attachments/assets/562b41d1-1089-4920-821d-8597d425df3c

Fixed the checkbox green outline and removed the cell border

**Comment by palisadoes** [comment]
Please fix the failing test and conflicting file

**Comment by pranavnathe** [comment]
@coderabbitai full review

**Comment by pranavnathe** [comment]
> Please fix the failing test and conflicting file

Resolved the failing test and fixed the conflicting file.

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. You overwrote the changes to the existing CSS file. 
`--brown-color` no longer exists as well as other incorrectly labeled variables
1. Please value the contributions of others in the collaborative approach of open source

**Comment by pranavnathe** [comment]
> 1. You overwrote the changes to the existing CSS file.
>    `--brown-color` no longer exists as well as other incorrectly labeled variables
> 2. Please value the contributions of others in the collaborative approach of open source

Apologies for overwriting the changes. I appreciate everyone's efforts and will fix this ASAP. Thank you for pointing it out!

**Review by palisadoes — APPROVED** [review]
