### PR TITLE
fix:orgDash not opening

### LINKED ISSUE #412: Cannot open orgdash
**Describe the bug**
On clicking the manage button on orglist it is not going to orgdash page, it gets back to orglist pagr

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an organization
2. click on the `manage` button

**Expected behaviour**

On clicking the `manage` button orgdash should be open.

**Actual behaviour**

it gets redirected back to orglist

**Screenshots**

https://user-images.githubusercontent.com/67755128/215266911-2f07daa5-cd58-4e5b-a70f-113e09c28f31.mov

**Additional details**
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1673430600985429

### PR DESCRIPTION
**Pull request by VenomFate-619**
**What kind of change does this PR introduce?**
it is a PR to fix the issue of the dashboard not opening.

**Issue Number:**

Fixes #412 

**Did you add tests for your changes?**

No

https://user-images.githubusercontent.com/67755128/217039917-4a3426a7-fd52-4166-8376-e5d7e2a3e9d4.mp4

[drive link](https://drive.google.com/file/d/1yUNK-dhTWMfgLFnCDGOjamHXNJABdQ3A/view?usp=share_link)

**Snapshots/Videos:**

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by VenomFate-619** [comment]
image

this test case was failing that why I removed the line  as well as that code is redundant as the spam feature is not yet built

**Comment by palisadoes** [comment]
@Kevoniat Please review

File: src/GraphQl/Queries/Queries.ts [hunk 1]
```diff
@@ -254,15 +230,8 @@ export const MEMBERSHIP_REQUEST = gql`
...
 export const ORGANIZATION_POST_LIST = gql`
-  query PostsByOrganization(
-    $id: ID!
-    $filterByTitle: String
-    $filterByText: String
-  ) {
-    postsByOrganization(
-      id: $id
-      where: { title_contains: $filterByTitle, text_contains: $filterByText }
-    ) {
```
Comment (noman2002) [inline src/GraphQl/Queries/Queries.ts:265]: Why we need to remove the filters ?

File: src/GraphQl/Queries/Queries.ts [hunk 2]
```diff
@@ -186,18 +172,8 @@ export const USER_ORGANIZATION_LIST = gql`
...
-    $filterByTitle: String
-    $filterByDescription: String
-  ) {
-    eventsByOrganization(
-      id: $id
-      where: {
-        title_contains: $filterByTitle
-        description_contains: $filterByDescription
-      }
-    ) {
```
Comment (noman2002) [inline src/GraphQl/Queries/Queries.ts:200]: Why we need to remove the filters ?

**Comment by noman2002** [comment]
@VenomFate-619 Please the video is corrupted please change it.

File: src/GraphQl/Queries/Queries.ts (hunk 1 above)
Comment (VenomFate-619) [reply src/GraphQl/Queries/Queries.ts:265]: refer this
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1674557631837709

File: src/GraphQl/Queries/Queries.ts (hunk 2 above)
Comment (VenomFate-619) [reply src/GraphQl/Queries/Queries.ts:200]: refer this
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1674557631837709

File: src/GraphQl/Queries/Queries.ts (hunk 1 above)
Comment (VenomFate-619) [reply src/GraphQl/Queries/Queries.ts:265]: image
I do not think we require any filter option as well, because we can get the info by id

if we need a filter then use this
```
    postsByOrganizationConnection(
      id: ID!
      where: PostWhereInput
      first: Int
      skip: Int
      orderBy: PostOrderByInput
    ): PostConnection
```

Comment (noman2002) [reply src/GraphQl/Queries/Queries.ts:265]: okay, got the point.

File: src/GraphQl/Queries/Queries.ts (hunk 2 above)
Comment (VenomFate-619) [reply src/GraphQl/Queries/Queries.ts:200]: image

same thing when this.
in the backend there is no such query mentioned to handle the where argument

**Comment by VenomFate-619** [comment]
quite weird the video is working fine for me.
I had reuploaded again check it.

**Comment by palisadoes** [comment]
> check it

It's still showing as corrupt.

image

**Comment by VenomFate-619** [comment]
added drive link

**Comment by Kevoniat** [comment]
The video work for me too

**Comment by Kevoniat** [comment]
> image
> 
> this test case was failing that why I removed the line as well as that code is redundant as the spam feature is not yet built

if the test is failing because it's redundant  when not remove the test and redundant   code

**Comment by AjayMaheshwari23** [comment]
Any Updates ?

**Comment by palisadoes** [comment]
@Kevoniat @noman2002 @Tajcore please review

File: src/GraphQl/Queries/Queries.ts (hunk 1 above)
Comment (beingnoble03) [reply src/GraphQl/Queries/Queries.ts:265]: @noman2002 @palisadoes @VenomFate-619 I have a doubt here.
- In `organizationsConnection.ts`, we are returning `[Organization]`. This implies we have no option for pagination here.
- In `postsByOrganizationConnection.ts`, we are returning `PostConnection`, which is an object of the form
```javascript
{
      pageInfo: {
        hasNextPage: boolean,
        hasPreviousPage: boolean,
        totalPages: integer,
        nextPageNo: integer,
        prevPageNo: integer,
        currPageNo: integer,
      },
      edges: posts,
      aggregate: {
        count: integer,
      },
}
```
Here, we have an option for pagination.
So, should we replace `PostConnection` with `[Post]` in `postsByOrganizationConnection.ts` and the `resolver` accordingly because we are nowhere using pagination using `talwa-api` in our entire codebase? With this we will be able to get filtered data, like we did in the case of filtering Organizations based on `name_contains`.
```
  query OrganizationsConnection($filter: String) {
    organizationsConnection(where: { name_contains: $filter }) {
      _id
      image
      creator {
        firstName
        lastName
      }
      name
      members {
        _id
      }
      admins {
        _id
      }
      createdAt
      location
    }
  }
```
Should we create an issue for this in `talawa-api`?

File: src/GraphQl/Queries/Queries.ts (hunk 2 above)
Comment (beingnoble03) [reply src/GraphQl/Queries/Queries.ts:200]: @noman2002 @VenomFate-619 we need to create `eventsByOrganizationConnection` for filtering out events with `where` parameter here. @palisadoes Should I open an issue for this in `talawa-api`?

**Review by palisadoes — APPROVED** [review]
